/// <reference types="nativewind/types" />

// CSS module declarations
declare module "*.css" {
  const content: any;
  export default content;
}

// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.
